REM INSERTING into TASTER
SET DEFINE OFF;
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Kerin O’Keefe','@kerinokeefe');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Roger Voss','@vossroger');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Paul Gregutt','@paulgwine ');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Alexander Peartree',null);
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Anna Lee C. Iijima',null);
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Virginie Boone','@vboone');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Michael Schachner','@wineschach');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Matt Kettmann','@mattkettmann');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Jim Gordon','@gordone_cellars');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Joe Czerwinski','@JoeCz');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Anne Krebiehl MW','@AnneInVino');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Jeff Jenssen','@worldwineguys');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Sean P. Sullivan','@wawinereport');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Susan Kostrzewa','@suskostrzewa');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Lauren Buzzeo','@laurbuzz');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Mike DeSimone','@worldwineguys');
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Carrie Dykes',null);
Insert into TASTER (TASTER_NAME,TASTER_TWITTER) values ('Fiona Adams','@bkfiona');
